// <auto-generated />
namespace CM.BalancedScoreboard.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dashboards_Readded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dashboards_Readded));
        
        string IMigrationMetadata.Id
        {
            get { return "201510071619202_Dashboards_Readded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
